### PR TITLE
Added Ability for ONLY redfor to squat

### PR DESCRIPTION
**Pull request by YourMajestySpitFire**
Added class squat in cfgFunctions
Added function squat
Added if statement in initPlayerLocal
(I messed up with line 12 initPlayerLocal.sqf sorry)

### CODE REVIEW

**Comment by Fusselwurm** [comment]
ftr, this seems to be the animation in question: https://youtu.be/qck_P6cMqGA?t=110

**Comment by YourMajestySpitFire** [comment]
> 
> 
> ftr, this seems to be the animation in question: https://youtu.be/qck_P6cMqGA?t=110

Since REDFOR is based on Russian Mafia I wanted to give them some gopnik vibe.
obraz

**Comment by nomisum** [comment]
already waiting for redfor to be eliminated stuck in animation. you need to be able to cancel it somehow. 😆

**Comment by nomisum** [comment]
i bet this isnt mp safe due to switchmove is only local... but i will make it work.

**Pull request merged**
